name: Build and Test

on:
  push:
    branches: ["master"]
    tags: ["[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      matrix:
        toolchain: [aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install necessary files
        if: ${{ matrix.toolchain == 'aarch64-unknown-linux-gnu' }}
        run: sudo apt-get install gcc-aarch64-linux-gnu

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.toolchain }}

      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.toolchain }}

      - name: Run tests
        if: ${{ matrix.toolchain == 'x86_64-unknown-linux-gnu' }}
        run: cargo test --verbose

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mexpr_parser.${{ matrix.toolchain }}
          path: target/${{ matrix.toolchain }}/release/mexpr_parser
          retention-days: 7

      - name: release new version
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: mexpr_parser.${{ matrix.toolchain }}
          files: target/${{ matrix.toolchain }}/release/mexpr_parser
          body_path: CHANGELOG.md

    permissions:
      contents: write
