name: Build and Test

on:
  push:
    branches: ["master"]
    tags: ["[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    permissions:
      contents: write
    strategy:
      matrix:
        toolchain: [
          # {target: aarch64-unknown-linux-gnu, container: quay.io/pypa/manylinux2014_x86_64},
          {target: x86_64-unknown-linux-gnu, container: quay.io/pypa/manylinux2014_x86_64}]
    container: ${{ matrix.toolchain.container }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Linker
        if: ${{ matrix.toolchain.target == 'aarch64-unknown-linux-gnu' }}
        run: yum install -y gcc-aarch64-linux-gnu

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.toolchain.target }}

      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.toolchain.target }}

      - name: Run tests
        if: startsWith( ${{ matrix.toolchain.target }} , 'x86_64' )
        run: cargo test --verbose --target ${{ matrix.toolchain.target }}

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mexpr_parser.${{ matrix.toolchain.target }}
          path: target/${{ matrix.toolchain.target }}/release/mexpr_parser
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          path: /tmp/artifacts

      - name: Debugger
        run: ls /tmp/artifacts

      - name: release new version
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /tmp/artifacts/*
          body_path: CHANGELOG.md

